### ISSUE TITLE
Redirect gateway.ipfs.io to ipfs.io

### ISSUE THREAD

**Issue by lgierth** [ipfs/infra#112]
gateway.ipfs.io has been obsolete for a while, and we should redirect everything to ipfs.io with status 301 Moved Permanently.

**Comment by jbenet** [comment]
Before we do i should bring this up: i've received strong indications from several people that have run services where users can add content or which proxy to other things that it is pretty important to have the _domain itself_ be clear that it's _user's_ content. 

Examples:
- [onion.link](//onion.link) - makes it clear it's a link, complaints dropped after changing from [onion.city](//onion.city)
- githubusercontent.com -  see https://developer.github.com/changes/2014-04-25-user-content-security/

I of course don't like that, but it's worth considering.

some options:
- ipfs.link
- keep gateway.ipfs.io (yuck so long)

cc @kyledrake for thoughts

**Comment by jbenet** [comment]
Before we do i should bring this up: i've received strong indications from several people that have run services where users can add content or which proxy to other things that it is pretty important to have the _domain itself_ be clear that it's _user's_ content. 

Examples:
- [onion.link](//onion.link) - makes it clear it's a link, complaints dropped after changing from [onion.city](//onion.city)
- githubusercontent.com -  see https://developer.github.com/changes/2014-04-25-user-content-security/

I of course don't like that, but it's worth considering.

some options:
- ipfs.link
- keep gateway.ipfs.io (yuck so long)

cc @kyledrake @virgil for thoughts

**Comment by kyledrake** [comment]
IIRC, Github had two concerns:

* People confusing *.github.com sites for github.com. You would get a flavor of this problem if I created "admin.github.com" and put a phishing login form on it.
* Any future security issues with browsers that could break the cross-domain security rules. It's largely theoretical but certainly isn't unhealthy to worry about it.

Problem 1 doesn't apply here, but problem 2 exists by default because of the way cross-domain security works. You will NOT safely be able to do any logins on ipfs.io, and it could be dangerous to use things like localStorage with browsers, as IPFS apps may do, as any other application will have access to it.

The only way to resolve this problem with today's browser security model is the HSHCA stuff I came up with for Neocities https://github.com/neocities/hshca

Surprisingly stable (for what it is) proxy: https://github.com/neocities/hshca-proxy

**Comment by kyledrake** [comment]
One interesting idea would be to have the front (ipfs.io) redirect to ipfs.io/ipns/ipfs.io, which would then be the web site, except loaded directly from IPFS. Or the latest hash (ipfs.io/ipfs/hash)

**Comment by jbenet** [comment]
> One interesting idea would be to have the front (ipfs.io) redirect to ipfs.io/ipns/ipfs.io, which would then be the web site, except loaded directly from IPFS. Or the latest hash (ipfs.io/ipfs/hash)

I'd be down with that. it would highlight how it's meant to work

**Comment by jbenet** [comment]
we _could_ ditch `ipfs.io` for the main site and use `ipfs-project.io` which redirects to `ipfs.io/ipns/ipfs-project.io` or something so it doesn't confuse people. (but maybe over analyzing)

**Comment by davidar** [comment]
> it could be dangerous to use things like localStorage with browsers, as IPFS apps may do, as any other application will have access to it

Yeah, I hit this problem myself with porting vector.im over to ipfs

> redirect to ipfs.io/ipns/ipfs.io

:+1: would be a good demonstration that websites can be hosted on ipfs

> we could ditch ipfs.io for the main site and use ipfs-project.io

Other domain names that are available: 

- ipfs.software
- ipfs.community
- ipfs.support
- ipfs.center
- ipfs.technology
- ipfs.sucks :p
